// Generated from the ContractDefinition objects beside each behavior runner.
export const DRIVER_CONTRACT_IDS = {
  batchPrimaryKeyDataflowContract: "drivers.batch-primary-key-dataflow",
  batchRefSmokeContract: "drivers.batch-ref-smoke",
  blobFilterContract: "drivers.blob-filter",
  bulkWriteLimitContract: "drivers.bulk-write-limit",
  clientRawContract: "drivers.client-raw",
  compoundJunctionContract: "drivers.compound-junction",
  compoundKeyContract: "drivers.compound-key",
  countAggregateWindowContract: "drivers.count-aggregate-window",
  createManyReturnFoldContract: "drivers.create-many-return-fold",
  cursorPaginationContract: "drivers.cursor-pagination",
  decimalExactnessContract: "drivers.decimal-exactness",
  distinctSkipWindowContract: "drivers.distinct-skip-window",
  fieldReferenceContract: "drivers.field-reference",
  fkIndexContract: "drivers.fk-index",
  fkIndexPlanContract: "drivers.fk-index-plan",
  fkIndexUpgradeContract: "drivers.fk-index-upgrade",
  forwardFkOrderingContract: "drivers.forward-fk-ordering",
  fullScalarRoundtripContract: "drivers.full-scalar-roundtrip",
  implicitReturningContract: "drivers.implicit-returning",
  jsonNullSentinelContract: "drivers.json-null-sentinel",
  likeEscapeContract: "drivers.like-escape",
  listJsonFilterContract: "drivers.list-json-filter",
  m2mDeleteManyStalenessContract: "drivers.m2m-delete-many-staleness",
  manyToManyContract: "drivers.many-to-many",
  mappedIndexContract: "drivers.mapped-index",
  nestedOrderByContract: "drivers.nested-order-by",
  nestedPaginationContract: "drivers.nested-pagination",
  nestedWriteContract: "drivers.nested-write",
  nestedWriteAdvancedContract: "drivers.nested-write-advanced",
  nestedWriteConcurrencyContract: "drivers.nested-write-concurrency",
  nestedWriteJsonEnvelopeContract: "drivers.nested-write-json-envelope",
  nonReturningMutationAtomicityContract:
    "drivers.non-returning-mutation-atomicity",
  omitContract: "drivers.omit",
  optionalRelationParityContract: "drivers.optional-relation-parity",
  orderingArrayCreateContract: "drivers.ordering-array-create",
  orderingPlanContract: "drivers.ordering-plan",
  partialIndexContract: "drivers.partial-index",
  partialIndexCoverageContract: "drivers.partial-index-coverage",
  partialIndexPredicateChurnContract: "drivers.partial-index-predicate-churn",
  partialIndexRefusalContract: "drivers.partial-index-refusal",
  polymorphicCollectionReadContract: "drivers.polymorphic-collection-read",
  polymorphicCollectionWriteContract: "drivers.polymorphic-collection-write",
  polymorphicMemberJunctionContract: "drivers.polymorphic-member-junction",
  polymorphicRelationContract: "drivers.polymorphic-relation",
  prismaParityContract: "drivers.prisma-parity",
  readPathRegressionContract: "drivers.read-path-regression",
  rawArrayTransactionContract: "drivers.raw-array-transaction",
  relationFilterMutationContract: "drivers.relation-filter-mutation",
  relationReadAggregateContract: "drivers.relation-read-aggregate",
  scalarRoundtripContract: "drivers.scalar-roundtrip",
  upsertAtomicityContract: "drivers.upsert-atomicity",
  vectorContract: "drivers.vector",
} as const;
