// Schema Validation Module

export {
  allRules,
  cascadeOnRequiredWarning,
  compoundFieldsExist,
  fkCardinalityMatch,
  fkFieldExists,
  fkOneToOneUnique,
  fkReferenceExists,
  fkReferencesUnique,
  fkRequiredForOwning,
  fkRules,
  fkTypeMatch,
  indexFieldsExist,
  indexNameUnique,
  junctionConfigConsistent,
  junctionFieldsDistinct,
  junctionFieldsValid,
  junctionTableUnique,
  modelHasFields,
  modelMappedNameValid,
  modelNameNotReserved,
  modelNameValid,
  modelRules,
  noCircularRequiredChain,
  noOrphanFkFields,
  polymorphicRelationWarning,
  polymorphicRules,
  validatePolymorphicRelations,
  relationHasInverse,
  relationNameUnique,
  relationPairFkSingleSide,
  relationRules,
  relationTargetExists,
  setNullRequiresNullable,
  validateFieldsSinglePass,
} from "./rules";
export { SchemaValidationError, isSchemaValidationError } from "./error";
export type {
  Schema,
  SchemaValidationIssue,
  SchemaValidationIssue as ValidationError,
  Severity,
  ValidationResult,
  ValidationRule,
} from "./types";
export {
  SchemaValidator,
  validateSchema,
  validateSchemaOrThrow,
  validatePolymorphicSchemaOrThrow,
} from "./validator";
